version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: springboot
    container_name: spring-OkMotoPecas
    ports:
      - "1000:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_USERNAME: okmotopecas
      SPRING_DATASOURCE_PASSWORD: motosenhas
    networks:
      - Ecommerce-network

  db:
    image: mysql:5.7
    container_name: mysql-OkMotoPecas
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "motosenhas"
      MYSQL_DATABASE: "ECommerceDataBase"
    ports:
      - "3306:3306"
    volumes:
      - /mnt/c/Users/atail/Documents/GitHub/Ecommerce/src/main/resources/db:/var/lib/mysql
    networks:
      - Ecommerce-network

  phpmyadmin:
    image: phpmyadmin:5.2.1
    container_name: phpmyadmin-OkMotoPecas
    environment:
      PMA_HOST: mysql-OkMotoPecas
    depends_on:
      - db
    restart: always
    ports:
      - "8080:80"
    volumes:
      - /mnt/c/Users/atail/Documents/GitHub/Ecommerce/src/main/resources/db:/etc/phpmyadmin/config.user.inc.php
    networks:
      - Ecommerce-network

networks:
  Ecommerce-network:
    driver: bridge